### ISSUE TITLE
[v3.3.0] Submit your work here

### ISSUE THREAD

**Issue by Asnxthaony** [Sorapointa/Sorapointa-Protos#1]
## Please submit your work in this issue.

**Recommended submission formats:**

```
PLACEHOLDER⇨value
```

**Comment by timing1337** [comment]
BOMOHKDHMNH⇨parent_quest_state

**Comment by c2c3vsfac** [comment]
IADFJHNFKIB⇨sub_channel_id
KGGPDKGDELG⇨client_tz
GEJJKDLGFPH⇨rydevicetype
BBAABEHNFOE⇨security_library_md5
DADMLCPIHKJ⇨next_add_timestamp
HIEMKEJOFPO⇨del_quest_id_list
BPCBOANPBHF⇨unlock_item_list
OGPLCBFDHCF⇨unlock_formula_list
GCEAKEMMJEA⇨selected_avatar_reward_id
CMMGKMMMOAL⇨coin_c_num
DABPFCPCNCB⇨max_passed_level
HMCJOLLKMMB⇨is_explored
BOMOHKDHMNH⇨parent_quest_state
MGBDKFMBGBO⇨add_quest_id_list
JHJNOPCPPAD⇨output_count
KDIPLNBHGDH⇨next_finish_timestamp
GJEECHKDEBD⇨finish_count
OOOJNABGHOM⇨queue_id
PJCKFNNIMNM⇨total_finish_timestamp
PBEFIJCEKMH⇨unlocked_module_id_list
JJPCFPAKFLM⇨levelup_reward_got_level_list
OONPDLMPLNC⇨miracle_ring_cd
ONJJJEPFKJI⇨teapot_spirit_pos
HFNOINGPMJP⇨safe_point_pos
IELHEAAMAKG⇨home_gather_id
GAJHLGKLBBK⇨seed_id
OKMNOFOHKOB⇨is_first_login_enter_scene
LIDGFMDDOOM⇨world_type
LLIJKLDBHNN⇨is_sc_open
BBHKBDDFPFE⇨valid_tower_record_num
AIFHPHDGEIE⇨best_floor_index
CPNOLKAKHEJ⇨total_star_count
LEMOMFLHBLA⇨best_level_index
ODPDLGEKIEM⇨last_read_pushtips_codex_id
JHLEHEOOGGB⇨refresh_interval
KNKFCOKMECI⇨max_boss_chest_num
IFHFHEHDOIO⇨reduce_durability
LDHNFNOGOGF⇨remain_durability
FJJLKJBOBAC⇨element_durability_attenuation
CJFKCNCGJLB⇨defense_id
JDEFHMKICPF⇨hit_halt_time_scale
EIGMFDMKADE⇨endure_break
MEFFADEPHBM⇨damage_shield
GGABJNLLEAJ⇨target_type
OOOLELPBDHJ⇨modifier_owner_id?1
IHCKJKLCICI⇨ability_caster_id?1
LNHIOLFMGCN⇨attackee_hit_entity_angle
OJHBMLIAPJN⇨attackee_hit_force_angle
HNKLIODEJAB⇨critical_rand
EBCNAAJAONF⇨attack_timestamp_ms
PIGBELICMMD⇨attack_count?
CAKEJCJKHOA⇨source_caster_id
KLNGDAMMFIF⇨hit_eff_level?9
LCKECJCKKJK⇨hit_retreat_angle_compat?9
OGILJCJPHPB⇨element_reaction_type
PHKFGIHELFG⇨element_source_type
DGBGNEHDODI⇨element_reactor_type
ECNBKHHADDJ⇨heal_amount
LCLOFCCIJKH⇨real_heal_amount
NOPKODKOHJK⇨is_mute_remote?
LLHABHMLNAH⇨scene_id
FCDDPFADNAI⇨avatar_ability_info
ALMECLCHHFA⇨revise_level
DKIMMKIHDCK⇨scene_level
PCIHJLPPHNJ⇨quest_var_seq
GNINCLBMMDJ⇨floor_open_time_map
FCDDPFADNAI⇨avatar_ability_info
EMAGOKCPPKN⇨weapon_ability_info
BLBEKMDGCMB⇨combat_entry_list
NLMPHBGMOEN⇨ability_entry_list
NOPKODKOHJK⇨is_attached_parent_ability?
DAIGHHPJHOO⇨unlock_hunting_city_list
NCMHMODIIKM⇨is_new_request?8
GJFNOPNMFNG⇨is_new_hunting?8

更新了一些。?代表应该是这个，但不太确定；?后面有数字代表只可能是这两个，但两个值似乎一直相同

**Comment by Simplxss** [comment]
> LLHABHMLNAH⇨scene_id

now i have two scene_id

![image](https://user-images.githubusercontent.com/44570052/206898149-af303e59-721f-4165-b789-e41a14659a40.png)

**Comment by Asnxthaony** [comment]
> > LLHABHMLNAH⇨scene_id
> 
> now i have two scene_id
> 
> ![image](https://user-images.githubusercontent.com/44570052/206898149-af303e59-721f-4165-b789-e41a14659a40.png)

It shoule be `prev_scene_id`

**Comment by terax6669** [comment]
```
OKMNOFOHKOB⇨is_first_login_enter_scene
LIDGFMDDOOM⇨world_type
LLHABHMLNAH⇨prev_scene_id
LFFBNEBMAAG⇨is_skip_ui
EBPACPNPKKJ⇨direction
IMNGNLLMEFJ⇨perform_id
HIEMKEJOFPO⇨del_quest_id_list
MGBDKFMBGBO⇨add_quest_id_list
JHLEHEOOGGB⇨refresh_interval
KNKFCOKMECI⇨max_boss_chest_num
ONLALCCKIEE⇨next_boss_chest_refresh_time
DADMLCPIHKJ⇨next_add_timestamp
BKBPGIAOBEL⇨to_state_hash
EOLDJAMHDHM⇨output_item_list
GDIBLADMJIC⇨dur_time
FLHNPFGNNBM⇨result_item_list
EHKFICBACKC⇨buy_limit
DBJCMMBHBNI⇨goods_id
CEOMHBNDAOP⇨max_level
DFEDKIOCOBL⇨min_level
PBEFIJCEKMH⇨unlocked_module_id_list
JJPCFPAKFLM⇨levelup_reward_got_level_list
GBDHFLEFJLG⇨accelerate_time
MLICEAKLOIH⇨cur_hp
MNNMOCIIEAJ⇨max_hp
NJILOBDEECC⇨from
EJHNJMBJBKG⇨to
JDPADLFFFDK⇨before_phase
GNAIDDMDEBN⇨after_phase
NEJLGBBFDPH⇨passed_dungeon
IFEPGCKHODL⇨received_reward
LPAKGGBBDNJ⇨del_team_resonance_id_list
MBJEEEEEJCE⇨add_team_resonance_id_list
ALELNLIODAO⇨be_killed_num_list
INHAGEELNNC⇨be_captured_num_list
BGCIGNEGBIN⇨ongoing_personal_line_list
BHLEGLEICFJ⇨can_be_unlocked_personal_line_list
AIFHPHDGEIE⇨best_floor_index
LEMOMFLHBLA⇨best_level_index
CPNOLKAKHEJ⇨total_star_count
DMILOONBELH⇨activity_type
AAEAECGPHBH⇨unlock_field_id_list
JJCEINFHKOG⇨unlock_deck_id_list
GEBHJAGKEID⇨unlock_card_back_id_list
IELHEAAMAKG⇨home_gather_id
GAJHLGKLBBK⇨seed_id
ONJJJEPFKJI⇨teapot_spirit_pos
HFNOINGPMJP⇨safe_point_pos
ILECHHKDIEM⇨is_on_scene
GENGJLPJCCN⇨is_player_cur_avatar
ONCNAJBJGKM⇨is_reconnect
FJOJFPPPOFP⇨filter_city_id
NADIOIJGPHE⇨finished_daily_task_num
OMEEMFJFKBH⇨temp_var_map
JFPLEDLNJPF⇨normal_var_map
GBKCGDPAJIE⇨is_crit
PJPCBIACFJK⇨is_resist_text
CJFKCNCGJLB⇨defense_id
FBDGCFAALFN⇨not_got_attachment_num
MANJMCPELLJ⇨not_read_num
KDLGLOIIINH⇨total_end_count
MJLMJBMGJPP⇨lock_reason_list
MOOKBLFKOLC⇨finish_dialog_list
KMJHIMBIGJF⇨finished_end_count
PPAOJCGAAEA⇨max_points
MFCHJHPJALD⇨curr_points
ODPDLGEKIEM⇨last_read_pushtips_codex_id
DCMJLCIFCEH⇨last_read_pushtips_type_id
NHOAGMGNEIM⇨normal_product_id
NIEBADLADMK⇨upgrade_product_id
AOMGCJOGGED⇨extra_product_id
MAAJDKMIODC⇨point
ELMNFBOLEOA⇨cur_cycle_points
FILCIPPAHHL⇨paid_platform_flags
KALOGHHMJJE⇨is_viewed
KODFJENCJLE⇨is_extra_paid_reward_taken
KKKNKNOLICI⇨scoin
ELDNONOCFMM⇨removed_watcher_list
FDMJACFMOLG⇨new_watcher_list
JHJNOPCPPAD⇨output_count
COMIGCMIPLE⇨output_time
NCEHJAAHOKM⇨wait_count
PJKHPCIMAID⇨unfinish_count
GJEECHKDEBD⇨finish_count
OOOJNABGHOM⇨queue_id
KDIPLNBHGDH⇨next_finish_timestamp
PJCKFNNIMNM⇨total_finish_timestamp
PGJIHELKCEA⇨total_page_count
LMCAADPAICM⇨page_index
BOMOHKDHMNH⇨parent_quest_state
PKJMEJKAPBI⇨exceeded_item_list
JDHFPCBOGFH⇨return_item_list
BFNHHNKOLBH⇨old_fight_prop_map
OIMPFCDCDGA⇨cur_fight_prop_map
MICPGJCIAPE⇨single_limit
OODCCOAIGHI⇨disable_type
JPHLECOIGKF⇨is_interpret
BFOGKOHIEEJ⇨is_submit
PKBCAOHGNLM⇨is_associate
```

**Comment by Simplxss** [comment]
NDPHNNOFEBL⇨qte_quality
JPICLIDLIEC⇨cook_count

IALPGNADFKA⇨old_append_prop_list
MGELABLMFOE⇨cur_append_prop_list

AMMAMKJDEMG⇨old_affix_level_map
IKJALGGLHOM⇨cur_affix_level_map

GGFCIPAKKDP⇨old_promote_level
MBEBIACJNBB⇨cur_promote_level

NMOPAGJFHOO⇨mcoin

GLPMIEMBGGL⇨gacha_times_limit
BLLMPAJNCPI⇨wish_max_progress
KEIJFMKAKDH⇨wish_item_id
NMOKGFGDFFC⇨wish_progress
OPGAHAGHEPF⇨new_gacha_random
JNOOHBNJFIE⇨is_gacha_item_new

JGPODDEKAPB⇨weapon_count_limit
NIKMCBLHFNJ⇨furniture_count_limit
OONMFCGDMMF⇨material_count_limit

GMMAIDIJOJM⇨deploy_furniure_list
DEIECJCAFLN⇨persistent_furniture_list

BOPIBKGAMID⇨continue_state
AHBGPMBHPMO⇨next_floor_id
MGHNDJAACME⇨cond_value
KPGBPDIJJJJ⇨cur_level_index
PMHCLPFPHBJ⇨cur_floor_id

BAKPEKIFJOA⇨total_extra_item_list
IAMGGFHOMEC⇨total_return_item_list
CDAFJDFHLKI⇨total_random_item_list

BGNIBLKCPCA⇨meet_cond_list

FHPCJMIILPA⇨black_uid_end_time

IPDBADAAHBA⇨talent_index
ODIOPLHJHAE⇨extra_level
LKNFMODMEIA⇨talent_type

PBMKNPCNBCK⇨secondary_sheet_id

// not ensure
NOIPAMJJIDL⇨has_path_to_target
OJHDJGAFDNN⇨is_async_load

**Comment by c2c3vsfac** [comment]
OOOLELPBDHJ⇨ability_caster_id
IHCKJKLCICI⇨modifier_owner_id
PIGBELICMMD⇨attack_count
ECHOFBLGIIO⇨hit_halt_time
HGJOKFPHMJJ⇨endure_delta
IPPHJMMELIG⇨hit_pos_type
HEIMDHBPFNF⇨hashed_anim_event_id
MNGCOAIGGAL⇨retreat_strength
DABGDGLAIKL⇨air_strength
以上是确定的

PBNENPBMNCI⇨is_mute_remote
JAEALAIOOID⇨score_limit
MPKAMIMDKOE⇨element_amplify_rate
NMCCLIKMOEN⇨layer
POIAEGJNEKP⇨last_deliver_item_time
HMAELBBOFDN⇨is_in_combat
PJPEEJACFJH⇨skip_floor_granted_reward_item_map
这些是比对3.2和3.3，去掉相同的字段，唯一类型相同的；我猜你们肯定也有类似的程序，可以验证一下。

**Comment by Xiaobin0860** [comment]
能分享一下dump协议的方法吗？我通过逆向发现里面没有反射的方法，逆向特定协议的序列化、反序列化方法，发现这里的proto文件tag不对啊，比如这个协议，3.3中文版本逆向tag应该是这样的
```protobuf
message GadgetInteractRsp {
  // enum CmdId {
  //   option allow_alias = true;
  //   NONE = 0;
  //   CMD_ID = 830;
  //   ENET_CHANNEL_ID = 0;
  //   ENET_IS_RELIABLE = 1;
  // }

  InteractType interact_type = 16;
  uint32 gadget_id = 88;
  int32 retcode = 56;
  uint32 gadget_entity_id = 8;
  InterOpType op_type = 64;
}
```

**Comment by Asnxthaony** [comment]
> ```proto
> GadgetInteractRsp 
> ```

See https://developers.google.com/protocol-buffers/docs/encoding?hl=en

**Comment by Asnxthaony** [comment]
> 能分享一下dump协议的方法吗？我通过逆向发现里面没有反射的方法，逆向特定协议的序列化、反序列化方法，发现这里的proto文件tag不对啊，比如这个协议，3.3中文版本逆向tag应该是这样的
> 
> ```proto
> message GadgetInteractRsp {
>   // enum CmdId {
>   //   option allow_alias = true;
>   //   NONE = 0;
>   //   CMD_ID = 830;
>   //   ENET_CHANNEL_ID = 0;
>   //   ENET_IS_RELIABLE = 1;
>   // }
> 
>   InteractType interact_type = 16;
>   uint32 gadget_id = 88;
>   int32 retcode = 56;
>   uint32 gadget_entity_id = 8;
>   InterOpType op_type = 64;
> }
> ```

See https://developers.google.com/protocol-buffers/docs/encoding?hl=en

**Comment by Asnxthaony** [comment]
Dear Outlanders,

Thanks to your support, Sorapointa-Protos has won the "HoYo Lovers Award 2022". Thank you for coming alongside us through this journey!
